# Generated by Django 4.0.5 on 2022-07-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(null=True)),
                ('name', models.CharField(max_length=256, null=True)),
                ('calories', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('proteins', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('fats', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
