# Generated by Django 4.0.5 on 2023-02-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='liquid',
            field=models.IntegerField(default=0),
        ),
    ]
