# Generated by Django 4.0.5 on 2023-02-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_day_liquid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='liquid',
            new_name='taken_liquid',
        ),
        migrations.AddField(
            model_name='day',
            name='goal_liquid',
            field=models.IntegerField(default=0),
        ),
    ]
