# Generated by Django 4.0.5 on 2023-02-26 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_liquid_day_taken_liquid_day_goal_liquid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='taken_liquid',
        ),
    ]
