# Generated by Django 4.0.5 on 2023-03-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_day_taken_liquid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_goal_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_goal_carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_goal_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_goal_liquid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_goal_proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_limit_calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_limit_carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_limit_fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_limit_proteins',
            field=models.IntegerField(default=0),
        ),
    ]
