# Generated by Django 4.0.5 on 2023-03-02 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_default_goal_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(choices=[('NONE', 0), ('READ', 1), ('READWRITE', 2)])),
                ('nutrition', models.IntegerField(choices=[('NONE', 0), ('READ', 1), ('READWRITE', 2)])),
                ('exercises', models.IntegerField(choices=[('NONE', 0), ('READ', 1), ('READWRITE', 2)])),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
