# Generated by Django 4.0.5 on 2023-03-04 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_permission_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='user_a',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='user_b',
        ),
        migrations.AddField(
            model_name='permission',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permission_receiver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='permission_sender', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
