# Generated by Django 4.0.5 on 2023-03-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_permission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='is_profile_public',
            field=models.BooleanField(default=False),
        ),
    ]
