# Generated by Django 4.0.5 on 2023-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_day_is_profile_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='is_profile_public',
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_public',
            field=models.BooleanField(default=False),
        ),
    ]
