# Generated by Django 4.0.5 on 2023-03-06 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_day_is_profile_public_user_is_profile_public'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('user', 'date')},
        ),
    ]
